// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/encomenda.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A palavra chave message é usada para definir a estrutura de dados que será transmitida,
// Se você observar, a estrutura é composta por: "tipo nome = numero_order"
// O número é usado pelo protobuf internamente, e deve ser atribuido a partir do 1, seguindo algumas regras, entre elas:
// O valor deve ser único
// Não altere os valores enquanto estiver usando a message
// Prefira usar valores entre 1 e 15, dessa forma irá economizar memória
// Você pode consultar todos os campos, assim como os rótulos dos campos na documentação: https://protobuf.dev/programming-guides/proto2
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpf  int32  `protobuf:"varint,1,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_encomenda_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encomenda_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_encomenda_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetCpf() int32 {
	if x != nil {
		return x.Cpf
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Encomenda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User       *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	CodProduto int32 `protobuf:"varint,2,opt,name=cod_produto,json=codProduto,proto3" json:"cod_produto,omitempty"`
}

func (x *Encomenda) Reset() {
	*x = Encomenda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_encomenda_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Encomenda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encomenda) ProtoMessage() {}

func (x *Encomenda) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encomenda_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encomenda.ProtoReflect.Descriptor instead.
func (*Encomenda) Descriptor() ([]byte, []int) {
	return file_proto_encomenda_proto_rawDescGZIP(), []int{1}
}

func (x *Encomenda) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Encomenda) GetCodProduto() int32 {
	if x != nil {
		return x.CodProduto
	}
	return 0
}

type EncomendaRastreio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encomenda   *Encomenda `protobuf:"bytes,1,opt,name=encomenda,proto3" json:"encomenda,omitempty"`
	CodRastreio int64      `protobuf:"varint,2,opt,name=codRastreio,proto3" json:"codRastreio,omitempty"`
}

func (x *EncomendaRastreio) Reset() {
	*x = EncomendaRastreio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_encomenda_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncomendaRastreio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncomendaRastreio) ProtoMessage() {}

func (x *EncomendaRastreio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encomenda_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncomendaRastreio.ProtoReflect.Descriptor instead.
func (*EncomendaRastreio) Descriptor() ([]byte, []int) {
	return file_proto_encomenda_proto_rawDescGZIP(), []int{2}
}

func (x *EncomendaRastreio) GetEncomenda() *Encomenda {
	if x != nil {
		return x.Encomenda
	}
	return nil
}

func (x *EncomendaRastreio) GetCodRastreio() int64 {
	if x != nil {
		return x.CodRastreio
	}
	return 0
}

var File_proto_encomenda_proto protoreflect.FileDescriptor

var file_proto_encomenda_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2c, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x63, 0x70, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x09, 0x45, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x1c, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x11, 0x45, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x6e,
	0x64, 0x61, 0x52, 0x61, 0x73, 0x74, 0x72, 0x65, 0x69, 0x6f, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x6e,
	0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x09, 0x65, 0x6e,
	0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x64, 0x52, 0x61,
	0x73, 0x74, 0x72, 0x65, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f,
	0x64, 0x52, 0x61, 0x73, 0x74, 0x72, 0x65, 0x69, 0x6f, 0x32, 0x4b, 0x0a, 0x10, 0x45, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x1a, 0x15, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x61, 0x73, 0x74,
	0x72, 0x65, 0x69, 0x6f, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_encomenda_proto_rawDescOnce sync.Once
	file_proto_encomenda_proto_rawDescData = file_proto_encomenda_proto_rawDesc
)

func file_proto_encomenda_proto_rawDescGZIP() []byte {
	file_proto_encomenda_proto_rawDescOnce.Do(func() {
		file_proto_encomenda_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_encomenda_proto_rawDescData)
	})
	return file_proto_encomenda_proto_rawDescData
}

var file_proto_encomenda_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_encomenda_proto_goTypes = []interface{}{
	(*User)(nil),              // 0: pb.User
	(*Encomenda)(nil),         // 1: pb.Encomenda
	(*EncomendaRastreio)(nil), // 2: pb.EncomendaRastreio
}
var file_proto_encomenda_proto_depIdxs = []int32{
	0, // 0: pb.Encomenda.user:type_name -> pb.User
	1, // 1: pb.EncomendaRastreio.encomenda:type_name -> pb.Encomenda
	1, // 2: pb.EncomendaService.SendEncomenda:input_type -> pb.Encomenda
	2, // 3: pb.EncomendaService.SendEncomenda:output_type -> pb.EncomendaRastreio
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_encomenda_proto_init() }
func file_proto_encomenda_proto_init() {
	if File_proto_encomenda_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_encomenda_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_encomenda_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Encomenda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_encomenda_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncomendaRastreio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_encomenda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_encomenda_proto_goTypes,
		DependencyIndexes: file_proto_encomenda_proto_depIdxs,
		MessageInfos:      file_proto_encomenda_proto_msgTypes,
	}.Build()
	File_proto_encomenda_proto = out.File
	file_proto_encomenda_proto_rawDesc = nil
	file_proto_encomenda_proto_goTypes = nil
	file_proto_encomenda_proto_depIdxs = nil
}
